### ISSUE TITLE
Sounds very interesting. A suggestion ...

### ISSUE THREAD

**Issue by g40** [andy31lewis/brySVG#1]
would be to add some pictures. Would be great to see how it looks. 

Thanks

**Comment by andy31lewis** [comment]
Thank you for your interest.
Sorry for the delay in responding.  The easiest way to see how it looks is to go to the [demo page](http://mathsanswers.org.uk/oddments/brySVG/demo.html) which is linked to at the top of the main Github page.  I think that is better than just pictures, because it is interactive.
