### ISSUE TITLE
Draggable (External) SVG Image - Information / Enhancement Request

### ISSUE THREAD

**Issue by kronenpj** [andy31lewis/brySVG#3]
Good day! I just found your library, along with the brython ecosystem writ large, and have a question. Background first - I'm creating a browser-UI for a playing card game and have decided to use SVG card images [1] which seem to work well with the svg-use tag pair. E.g.:
```
<svg ...>
<use href="svg-cards.svg#joker_red" x="40" y="12"/>
</svg>
```

Is it possible to translate that usage into brySVG methods? If not, would that be a reasonable feature request for brySVG?

[1] https://github.com/htdebeer/SVG-cards

**Comment by kronenpj** [comment]
I'm able to place cards by using this construct:

```
from browser import document, svg
import brySVG.polygoncanvas as SVG
SVGRoot = document["card_table"]

canvas = SVG.CanvasObject("95vw", "95vh", "cyan", objid="canvas")
SVGRoot <= canvas

canvas.mouseMode = SVG.MouseMode.DRAG
piece = svg.use(href="/static/svg-cards.svg#spade_9")
canvas.addObject(piece)
piece = svg.use(href="/static/svg-cards.svg#heart_5")
canvas.addObject(piece)
canvas.translateElement(piece, (20, 20))
```

Where the HTML file is:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Application Home Page</title>
    <script type="text/javascript" src="/static/brython.min.js"></script>
    <script type="text/javascript" src="/static/brython_stdlib.js"></script>
    <script type="text/javascript" src="/static/brySVG.brython.js"></script>
    <script type="text/python" src="/static/dragdrop2.py"></script>
</head>
<body onload="brython(1)">
    <div id='card_table'></div>
</body>
</html>
```

I can drag with a mouse but it never lets go unless another object happens to be where you click. Touch doesn't work the way one might expect. There's no touch and drag, it's double-touch and no release, similar to the mouse behaviour.

**Comment by andy31lewis** [comment]
Hello kronenpj

Thank you for raising this - I have never used the svg `use` element, but I can see how it could be useful. (Thank you also for pointing me to the rather nice deck of cards you are using.)

I have pushed a commit which includes a new class `UseObject`. (Not sure whether that is the best name - maybe `ImportedObject` would be better, what do you think?) This takes 3 parameters: `href`, `topleft` and `angle` - their use should be obvious from the example.

Now your code can be rewritten as:
```python
from browser import document, svg
import brySVG.polygoncanvas as SVG

SVGRoot = document["card_table"]
canvas = SVG.CanvasObject("95vw", "95vh", "cyan", objid="canvas")
SVGRoot <= canvas

canvas.mouseMode = SVG.MouseMode.DRAG
piece = SVG.UseObject(href="/static/svg-cards.svg#spade_9")
canvas.addObject(piece)
canvas.translateObject(piece, (40,0))
piece = SVG.UseObject(href="/static/svg-cards.svg#heart_5", topleft=(20, 20))
canvas.addObject(piece)
piece = SVG.UseObject(href="/static/svg-cards.svg#diamond_queen", topleft=(400, 100), angle=45)
canvas.addObject(piece)
```
You should find that dragging works correctly. Cards can be positioned when created using the `topleft` parameter; if you want to move them after creation, you can now use the `canvas.translateObject` method, rather than `canvas.translateElement` which will mess up dragging.

This very much a first attempt - lots of things won't work yet, but I wanted to do something quickly to enable you to make progress on your project.  If you come across things you would like to do which don't work, please let me know.  I will be testing various methods as well, so expect more commits in the next few weeks.

I notice that you had accessed brySVG by including the package file `brySVG.brython.js`. That's my preferred method too, so I have pushed an updated package file as well. However I have had trouble with outdated versions persisting in the indexedDB cache (more so in Firefox than in Chrome), so sometimes I have to clear that cache from within Developer Tools before the new version is recognised.

Also, if you don't want to keep downloading new versions of the package, try including the line:
`<script src="https://cdn.jsdelivr.net/gh/andy31lewis/brySVG@master/brySVG.brython.js"></script>` instead of using a local file as the `src`. This should always get the latest version.

Best wishes

Andy

**Comment by kronenpj** [comment]
Andy,

  Thank you for the quick turn-around on this request! It certainly works a lot better for my purpose now.  It's my first time using svg-use so I'm right there with you. 

  On a tablet-like device, I'm hoping for the tap-and-flick style UI interaction. Unfortunately I need to 'double tap' to grab the card. However, it doesn't hang on to the mouse cursor or otherwise do weird things. :1st_place_medal: 

  I've been fighting with SVG and the DOM today so this is a welcome update indeed. I don't seem to have an opinion between `UseObject` and `ImportedObject`. They both "work" as such, `UseObject` invokes the HTML element and `ImportedObject` is certainly what it is. My only suggestion is to be consistent with the rest of the library.

  I'm aware of the alternate method of obtaining the library, for the moment I'm content keeping the local copy current. The CDN URLs are present but commented out in the files I'm working on.

Cheers!
-Paul

**Comment by andy31lewis** [comment]
Hello again Paul

I've been doing some reading around about `use` elements, and experimenting.  The weird behaviour when dragging on a touchscreen is related to this issue:
https://stackoverflow.com/questions/63699493/javascript-touchmove-event-not-working-after-event-target-moved-in-dom-in-touchs
So if you care to download the code rather than just the package file, and comment out line 1029 in dragcanvas.py (`self <= self.mouseOwner`) then dragging on touchscreens should work normally.  Unfortunately this is not really a solution, as dragged objects will not be brought to the top and so will slide under any objects above them.  But it may help you for the moment.

I will look into this further, but I don't want to change the drag mechanism for all types of object just to accommodate `UseObjects`.

More to follow, but probably not today as I have several things on.

Andy

**Comment by kronenpj** [comment]
Very interesting. Thank you - I have that patch working. Fortunately I don't (think I) need to use the drag mechanism on other aspects of the application. I'm still struggling with other aspects of SVG & gaining access to attributes, but this part is working well for me.

**Comment by andy31lewis** [comment]
Hi again
Just reporting on the experiments and commits I have made today.  Firstly, `use` elements do not have to come from an external file - they can simply be re-using an element on the current canvas, referenced by id.  (So `UseObject` is a better name than `ImportedObject`.) So I have made it easier to give objects an id by introducing an `objid` parameter for all shape elements. The following test is interesting because dragging the original shape also moves any `UseObjects` based on that shape (but not vice-versa), which seems like it might be useful in some circumstances. It also shows that `topleft` is not an appropriate name for the `UseObject` parameter; I am going to change it to `origin`.
```python
from browser import document
import brySVG.polygoncanvas as SVG
SVGRoot = document["card_table"]
canvas = SVG.CanvasObject("95vw", "95vh", "cyan", objid="canvas")
SVGRoot <= canvas

canvas.addObject(SVG.CircleObject(centre=(0,0), radius=30, objid="circle"))
canvas.addObject(SVG.PolygonObject([(45,-30), (30,0), (60,0)], objid="triangle"))

canvas.addObject(SVG.UseObject("#circle", (200,150)))
canvas.addObject(SVG.UseObject("#triangle", (200,150)))
canvas.addObject(SVG.UseObject("#circle", (290,150)))

canvas <= SVG.RectangleObject([(0,0), (400,300)], linecolour="blue", fillcolour="none")
canvas <= SVG.PointObject((200,150), colour="blue")
canvas.fitContents()
canvas.mouseMode = SVG.MouseMode.DRAG
```
To prevent the original objects from appearing on the canvas, they can be wrapped in `<defs>,</defs>` tags.  To facilitate that, I have introduced a new `Definitions` class. So the original objects above could be written as:
```python
canvas <= SVG.Definitions([
SVG.CircleObject(centre=(0,0), radius=30, objid="circle"),
SVG.PolygonObject([(45,-30), (30,0), (60,0)], objid="triangle")
])
```
`Definitions` can also take a parameter `filename`, in which case it reads in objects from an `svg` file. So by including a line
`canvas <= SVG.Definitions(filename="/static/playingcards.svg")`, we can access the cards simply by their id, eg `piece = SVG.UseObject(href="#heart_5", origin=(20, 20))`. The advantage of importing the file into the canvas like this is that `getBBox()` now knows the position and size of the object, so that, for example `canvas.fitContents()` now works. (When the cards were being read from the external file, `getBBox()` returned a height and width of zero.)

(To use the file in this way, it has to be modified slightly by removing from the beginning everything up to and including `<defs>`, and removing from the end `</defs></svg>`. I renamed the modified version `playingcards.svg`.)

Knowing the size and position of the object also allows implementing the solution to the dragging problem on touchscreens which was suggested in the StackOverflow link above: ie covering each `UseObject` with a transparent rectangle which acts as the target for the touch events. (This is a solution which brySVG already uses for objects with no fill, so wasn't too hard to extend to `UseObjects`.)

So now the following code should produce dragging that works correctly even on touchscreens:
```python
from browser import document, svg
import brySVG.polygoncanvas as SVG
SVGRoot = document["card_table"]
canvas = SVG.CanvasObject("95vw", "95vh", "cyan", objid="canvas")
SVGRoot <= canvas

canvas <= SVG.Definitions(filename="/static/playingcards.svg")
canvas.addObject(SVG.UseObject(href="#spade_9"))
canvas.addObject(SVG.UseObject(href="#heart_5", origin=(20, 20)))
canvas.addObject(SVG.UseObject(href="#diamond_queen", origin=(200, 150), angle=45))

canvas.fitContents()
canvas.mouseMode = SVG.MouseMode.DRAG
```
(Note that setting the `mouseMode` has been moved to the end since it is this that triggers the creation of the transparent "touch-targets")

So you should now be able to go back to using the package file - the hack of commenting out a line is no longer needed.  If this all works for you, great - but on the other hand if you have any more problems or questions, please ask either in this issue, or by starting a new one if that is more appropriate.

Cheers
Andy

**Comment by kronenpj** [comment]
Andy,

  I really appreciate you continuing to work on this. I've git pulled and updated and the code but have hit a bit of a snag. It appears that `update()` is being called before `self.pointList` is declared.

```python
Traceback (most recent call last):
  File http://localhost:5000/__main__ line 189, in <module>
    update_display()
  File http://localhost:5000/__main__ line 153, in update_display
    place_cards(discard_deck, kitty=True)
  File http://localhost:5000/__main__ line 123, in place_cards
    piece = PlayingCard(
  File http://localhost:5000/__main__ line 42, in __init__
    self.update()
  File http://localhost:5000/__main__ line 45, in update
    super().update()
  File http://localhost:5000/static/Lib/site-packages/brySVG/dragcanvas.py line 360, in update
    [(x1, y1), (x2, y2)] = self.pointList
AttributeError: pointList brython.min.js:7:207754
...
```
Do I need to call `getPointList()` at some point or is something missing from `update()`? I notice that the other objects declare `self.pointList` in `__init__()`. It looks like this could safely be put in `__init__()` but I'm not sure what failures are possible that might warrant a `try` block:
```python
    bbox = self.getBBox()
    self.pointList = [(bbox.x, bbox.y), (bbox.x+bbox.width, bbox.y+bbox.height)]
```
or
```python
    self.getPointList()
```

With either of those, it works nicely. I don't see a behaviour difference between the two, so I'll leave it to you to finalize this one. :)

I've also moved to a `PlayingCard` class that extends `UseObject` because I both needed more attributes and was trying to figure out how to register for events without replacing what already exists. So I'm thinking about hijacking `update()` and riddling it with conditionals to try to suss out what happened, but I feel like that's not the right approach. I'm also pretty sure that's not the intended purpose. In short - I'm sure I'm missing something on how to act upon events. That's a bit out of scope for this issue though.

-Paul
PS: If you're remotely interested, I'm keeping the code here: [Pinochle](https://gitlab.com/iqpinochle/pinochle). I'll commit a revision later tonight with the changes I made from this update.

**Comment by andy31lewis** [comment]
Hi Paul

Looking at your code, I see that you are calling `update` yourself from within your `PlayingCard.__init__`.  It's not really intended to be called by a user - I suppose by Python convention it should be named `_update`.

The reason that `pointList` and `update` are not referenced in `UseObject.__init__` is that unlike for other objects, `pointList` isn't user defined - it is obtained using `getBBox`.  But `getBBox` doesn't work until the object has been added to the canvas (so, not at the `__init__` stage) - it just returns zeros.

So as a special case for `UseObjects`, `getPointList` and `update` are carried out in `canvas.addObject` (see lines 854-856 in `dragcanvas.py`).

To decide on the best way forward, I need to know why you need to call `update` yourself rather than letting brySVG handle it.

Andy

PS Looking in the GitLab repository I see you have also made use of my Dominate game.  Nice to see things are being used!

**Comment by kronenpj** [comment]
Andy,

  Short answer - I have no clue, but the code behaves how I intend it to. I'm experimenting until something works, so I'm open to alternatives.

  I found that I can register for the `click` event only when adding an object using `<=`, but when I do that `update()` isn't called and when I click on such an object I see:
```
Traceback (most recent call last):
  File http://localhost:5000/__main__ line 78, in flip_card
    obj.flip_card()
  File http://localhost:5000/__main__ line 66, in flip_card
    self.update()
  File http://localhost:5000/__main__ line 45, in update
    super().update()
  File http://localhost:5000/static/Lib/site-packages/brySVG/dragcanvas.py line 360, in update
    [(x1, y1), (x2, y2)] = self.pointList
AttributeError: pointList
```
Which leads me to start working out why. 

Yes, I started using Dominate for some insights and suggestions. I noticed that it doesn't use `brySVG` so it's useful for the in-the-weeds details.

-Paul

**Comment by andy31lewis** [comment]
Paul,
OK this is interesting (not that I know how to play Pinochle...), so I downloaded your latest `dragdrop.py` and had a look.
The `update` issue is simply that you have a method called `update`, which will override `UseObject.update`, so you have called that using `super`.  To solve this, you just need to rename your `update` to something else, and remove line 46 (`super().update`).

Another issue is that at line 77 you get the card using `obj = document[event.target.id]`.  But that will only give you the SVG element, not a Brython object.  (This holds in general for HTML or SVG elements, and any Brython code - it is not specific to brySVG.) So brySVG gets round that by maintaining a dictionary of objects on the canvas.  So line 77 needs to change to `obj = canvas.objectDict[event.target.id]`.

Now objects get added to `canvas.objectDict` during `canvas.addObject`, so line 137 needs to be `canvas.addObject(piece)`.
You were finding that this caused the click event to be ignored.  But that is not because of any clash of events - you can have several handlers defined for the same event.  The reason was simply that in solving one problem (dragging on touchscreens) by overlaying the cards with "hittargets" (transparent rectangles), I had created another: the click is received by the hittarget, not the card itself. (The reason the problem went away when using <=, is that the hittargets are created during `canvas.addObject`.

So in the latest commit I have cured that problem by making sure that clicks on hittargets are forwarded to the underlying object.

With those changes dragging works correctly for me (including on touchscreen). And clicking/tapping on the facedown cards at the top turns them over. I need to polish up this latest commit, but it is working.

I notice that sometimes when a card is turned over, there is nothing there. But I think tht must be a problem with your gameplay.

I hope that helps,

Andy

**Comment by andy31lewis** [comment]
Hi Paul

I've had a look through the whole of `dragdrop.py` now.  The layout and all the comments make it really easy to follow.  Here are a few more points which I hope you will find helpful.  I'll be away for a couple of days, so this will be the last for a while.

- Line 138: `object.attrs["attribute"]` is for getting/setting built-in SVG/HTML attributes such as `img.attrs["src"]`. But `fixed` is an attribute I created, so this should just be `piece.fixed = True`
- Line 194: `discard_deck = sample(deck, k=4).sort()` shouldn't work (but it does). In CPython `discard_deck` would be `None`.  I have reported this as a bug in Brython; if Pierre fixes it your code will stop working, so it might be wise to change it to `discard_deck = sorted(sample(deck, k=4))`.
- Line 154: `canvas.deleteAll()` does the same as your `clear_canvas()` and also empties the `canvas.objectDict`, so probably better to use that.

The remaining points are not vital:
- For CSS properties you can use `object.style.property` as an alternative to `object.style["property"]`. I prefer the first but you may prefer the second.
- Line 42: You could bind a click on a `PlayingCard` directly to the `self.flip_card` method - you just need to change line 64 to `def flip_card(self, event=None):`. Then you don't need a separate `flip_card` function.  (The purpose of `=None` is in case you want to call `somecard.flip_card()` from elsewhere in code, not in the context of an event.) 

Cheers

Andy

**Comment by kronenpj** [comment]
Andy,

  I've made all the changes you suggest, at least for the code that still exists :). After everything, it pretty much works as I need/want it to right now. One item in particular I still don't quite understand is that I had to avoid removing and re-adding objects from/to `canvas`. That approach broke event handling / propagation. I wanted to refactor that portion so it made sense to try a different approach.

I did add a few lines to `CanvasObject.endDrag` to propagate events to dragged objects:

```diff
diff --git a/brySVG/dragcanvas.py b/brySVG/dragcanvas.py
index 9a631d4..da080ea 100644
--- a/brySVG/dragcanvas.py
+++ b/brySVG/dragcanvas.py
@@ -1085,6 +1087,12 @@ class CanvasObject(svg.svg):
         if self.edgeSnap: self.doEdgeSnap(self.mouseOwner)
         elif self.vertexSnap: self.doVertexSnap(self.mouseOwner)
         self.mouseOwner = None
+        obj = self.getSelectedObject(event.target.id)
+        if obj and hasattr(obj, "hitTarget"):
+            if "mouse" in event.type:
+                obj.dispatchEvent(window.MouseEvent.new('mouseup'))
+            if "touch" in event.type:
+                obj.dispatchEvent(window.TouchEvent.new('touchend'))
 
     def preparePan(self, event):
         x = event.targetTouches[0].clientX if "touch" in event.type else event.clientX
```
I don't know if I "got it right" this way but in my usual way, I made it work. Tweak / fix it as you see fit.

I'm fairly satisfied with the state of the proof-of-concept UI. I'll be continuing work on the API implementation and working it into the UI.

Thank you once again! I hope you had a good few days off from my perstering :)
-Paul

**Comment by kronenpj** [comment]
Of course, I'm happy to continue testing updates and the final product.

**Comment by andy31lewis** [comment]
Hi Paul

I have had a look at your latest `dragdrop.py`.  A few comments:
- Using DOM attributes like `parentElement`, `childNode` etc gives you the plain SVG element rather than the Brython object with whatever extra methods and attributes have been defined on it, so is best avoided so far as possible. (This is the same as I mentioned in a previous post with regard to using `document[id]`.)
- So in line 83, `parent_canvas = obj.parentElement` means `parent_canvas` is an SVG `<svg>` element, not a Brython/brySVG `CanvasObject`, and so has no `deleteObject` method (etc). This can be fixed by using `parent_canvas = obj.canvas` (the `addObject` method gives each object added to a canvas a reference to that canvas).
- Similarly in line 204 `[x for x in target_canvas.childNodes if deck_type in x.id]` gives you a list of SVG `<use>` elements, not Brython `PlayingCard` objects. To access the `PlayingCards`, it can be replaced by `[x for (objid, x) in target_canvas.objectDict.items() if deck_type in objid]`.
- And similarly in line 91.
- There are a couple of other places where you could avoid using DOM attributes directly, though in these cases it doesn't matter: lines 207 & 208 could just be `(x, y) = node.origin` and line 234 could be `if len(canvas.objectDict) == 0:` or simply `if not canvas.objectDict:`.

Coming onto the lines you added to the `endDrag` method, I see why you need them - to forward `mouseup` and `touchend` events from `hittargets` to the associated `PlayingCard`.  I would rather find a more general solution, so I have amended my event handling on `hittargets` - before, just `clicks` were forwarded to the underlying object, now all the main `MouseEvents` and `TouchEvents` are forwarded, including `mouseup` and `touchend`.  So your patch should no longer be needed. It would be helpful if you could test this.

As usual, I hope this is helpful,

Andy

**Comment by kronenpj** [comment]
As ever, thank you for your suggestions. An update is available for your reviewing pleasure :).

Most of the time when I've used the DOM attributes rather than the Python object attributes, I've looked at what the browser reports as the attributes without looking closely at the object definition first. That's partly because I'm not sure if it's an attribute brySVG added or something unhelpfully undocumented from brython / SVG DOM documentation.

The update to `hittarget` event handling works as expected, at least for my use case.

**Comment by andy31lewis** [comment]
Unfortunately I wasn't able to run the latest update, because you must have also changed the html document (`document["card_definitions"]` gives me a `KeyError`), and I couldn't find the new version.

However, being introduced to these playing cards has encouraged me to write a small puzzle using the cards, which you can find at http://mathsanswers.org.uk/games/playingcards/graeco_latin.html. You might get some ideas from looking at the code which you will find by viewing the source and clicking through to `graeco_latin.py`

(Just looking through your code without running it, one suggestion I would make is that you might find it easier to bind the `mouseup` and `touchend` handlers to the canvas, rather than the playing card. That would mean that they would fire after `canvas.endDrag` rather than before it, so the coordinates of the card will have been updated.  That's what I usually do, anyway - for example see `onMouseUp` in the puzzle mentioned above.)

All the best

Andy

**Comment by kronenpj** [comment]
Andy,

I'll definitely take a look to see how you wrote this. I can already see how I've made things more complicated than they really need to be. The HTML file is under /pinochle/templates though it really doesn't need to be. There are now four 'stages' of card play, the button at the top-left will advance you through them.

Unfortunately, as pushed to mathsanswers, the HTML is accessing an older version of brySVG:
```python
Traceback (most recent call last):
  module __main__ line 17
    class PlayingCard(SVG.UseObject):
AttributeError: 'module' object has no attribute 'UseObject'
```
Once I update to the current version, I see a lot of errors on the console like this:
```javascript
Javascript exception: InternalError: too much recursion
    check_nb_args http://localhost:5000/static/brython.min.js:7
    isinstance http://localhost:5000/static/brython.min.js:7
    $getitem http://localhost:5000/static/brython.min.js:7
    __getitem__ http://localhost:5000/static/brython.min.js:7
    $getitem http://localhost:5000/static/brython.min.js:7
    __getitem__ http://localhost:5000/static/brython.min.js:7
    $getitem http://localhost:5000/static/brython.min.js:7
    __getitem__ http://localhost:5000/static/brython.min.js:7
    $getitem http://localhost:5000/static/brython.min.js:7
    __getitem__ http://localhost:5000/static/brython.min.js:7
...
    $getitem http://localhost:5000/static/brython.min.js:7
    __getitem__ http://localhost:5000/static/brython.min.js:7
    $getitem http://localhost:5000/static/brython.min.js:7
    __getitem__ http://localhost:5000/static/brython.min.js:7
    $getitem http://localhost:5000/static/brython.min.js:7
    __getitem__ http://localhost:5000/static/brython.min.js:7
    $getitem http://localhost:5000/static/brython.min.js:7
    __getitem__ http://localhost:5000/static/brython.min.js:7
    $getitem http://localhost:5000/static/brython.min.js:7
    __getitem__ http://localhost:5000/static/brython.min.js:7
brython.min.js:7:282545
```
and
```python
recursion error ? true brython.min.js:7:282622
```

I've looked through the code a few times but can't find where recursion is even used. It's likely that the amount of computation being done to iterate over the cards is triggering that error.

Paul

**Comment by andy31lewis** [comment]
Hi Paul

Are you saying that if you click on the link in my last post, you get these errors? That's weird if so, because I have just tried it in 4 different browsers and it works in them all (though it was quite slow to load the first time in a couple of them which I haven't used for a long time).

If it won't work for you try clearing your browser cache and indexedDB storage?

Andy

**Comment by kronenpj** [comment]
Clearing the caches etc. fixed both problems. 

-Paul

**Comment by andy31lewis** [comment]
Well I'm glad you solved that problem. And did you solve the puzzle?! :)

I've run your update now and it seems to work.  I can turn cards over in "reveal "mode (though, as before, sometimes when the card is turned over there is nothing there - but that may be deliberate?), and I can drag them onto the blank outlines in "meld" and "trick" modes.  The refresh and clear buttons don't seem to do anything in any mode - maybe they are not meant to yet?

And I decided that the blank outlines look better than rectangles, so now my puzzle uses them too. :)

Andy

**Comment by kronenpj** [comment]
Yes, I was able to solve the puzzle on the first try. Perhaps I've seen it before or it's similarity to Sudoku made it easier. :)

In 'reveal,' there should be four cards and no blanks, so that's interesting and I'm not seeing that behaviour. Interestingly, in Firefox, the DOM Inspector doesn't update the HREF attribute when the face is revealed. They should be random card faces.

In 'meld' you should be able to click or drag onto empty slots above, so that appears to be functioning correctly for you. In 'trick' mode, I require that you drag cards. I don't (yet) have an undo feature and the intent is that when a card is dropped onto one of the four blanks, it's revealed to the other three players in (near) real-time. Though in real-life game-play you could grab the card back and replace it. 

I'm really getting to the point where the back-end needs to be connected and I'm making slow progress - I'm new at API creation too, so thinking through how it should work is slow going.

The refresh and clear buttons call `update_display` and `clear_display` and are only there for testing to see that the cards are displayed as they're intended. So them not appearing to do anything is a good thing. If you click refresh after sending a card to the top in 'trick' mode, you'll see a slight shift when the lower deck re-arranges due to the now-missing card.

I'm still studying your implementation for graeco_latin to see where I can glean improvements. 

I'm satisfied that your improvements so far have addressed this bug report. If you'd like, we can close this request and continue this collaboration via email.

-Paul

**Comment by andy31lewis** [comment]
Yes, that seems like a good idea.
