### ISSUE TITLE
Chrome and Firefox Rendering Inconsistency

### ISSUE THREAD

**Issue by kronenpj** [andy31lewis/brySVG#4]
Greetings Andy!

  I hope you've been doing well!

  While creating selenium tests for the pinochle project, I noticed a discrepancy on how the two browser engines render objects. 
This was a novelty when I initially noticed it because it doesn't affect usability, but programmatic access is adversely affected. I don't know if this is really a problem with Firefox or actually with brySVG.

  I tried to find an example in the Brython demos, but they don't exhibit the same behaviour. Also, the main brySVG demo page is rendered the same on the two browsers. It appears to be specific to the new `<use>` tag. I used [this](http://mathsanswers.org.uk/games/playingcards/graeco_latin.html) page to demonstrate the problem.

I've attached two screen shots showing Chrome and Firefox with the upper-left Jack of Hearts highlighted in the developer utility. Note the difference in where the browsers represent the boundaries. 

![Screenshot-Chrome](https://user-images.githubusercontent.com/286689/121437043-2ab62680-c971-11eb-8fd2-3f5f94b268ed.png)

![Screenshot-Firefox](https://user-images.githubusercontent.com/286689/121437046-2be75380-c971-11eb-8e2f-7bdd9fad91c2.png)

**Comment by andy31lewis** [comment]
Hello Paul

Good to hear from you.  Sorry I haven't contributed to your project lately, I have been busy with a new one of my own ([https://github.com/andy31lewis/brycharts](https://github.com/andy31lewis/brycharts), if you are interested).  I have been following your progress, though.

I have noticed this oddity before - I think this is just a Firefox thing.  Try going to the `<use>` demo at MDN, [https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/SVG/Element/use/_sample_.Example.html](https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/SVG/Element/use/_sample_.Example.html). (It will be easier to view this with the developer tools window at the bottom of the screen rather than the right hand side.)

If you inspect the three elements (a `<circle>` on the left, and two `<use>` elements which are copies of it to the right), in Chrome you will see the highlight positioned over each element, whereas in Firefox it isn't. As far I can see this is because Firefox is moving the highlight 10 pixels to the right rather than 10 SVG units.  In the cards example, the problem is worse, because the originals of the cards aren't in the same `<svg>` element as the `<use>` elements, so the scaling is also different.

As you say, this doesn't affect users since they will never see these highlights.  But I'm curious as to what you are doing which makes it a problem for you the programmer? Since you are working in SVG units, whereas the tooltip on these highlights gives the measurements in pixels, I'm not sure why you would want to look at them?  If you would like me to look at the specific issue you are trying to solve, I am happy to do so.

Best wishes,

Andy

**Comment by kronenpj** [comment]
I will look at your new project - just the name sounds interesting :)

I've assembled a [Selenium](http://selenium.dev) test for the user-interface. Manually playing four hands of Pinochle gets tedious when there's a problem near the end of the round. :)  While it finds objects by XPATH or ID attribute, interacting with them often fails because of this problem. E.g. sometimes 'dragging' a card triggers an exception because one of the coordinates is outside the window boundary. Other times I see an error where the element cannot be scrolled into view, even though there is no scroll bar and the item is in the middle of the page.

Ultimately it's not really a problem for me as both Chrome and Edge behave properly and I can use both for the UI testing. I wasn't sure if there was a workaround but it sounds like it would be easier to report this as a bug against Firefox and hope it's not part of their anti-fingerprinting efforts.
