### ISSUE TITLE
TextObject should allow access to linecolour and fillcolour attributes

### ISSUE THREAD

**Issue by kronenpj** [andy31lewis/brySVG#5]
In the brySVG documentation, the `linecolour`, and `fillcolour` attributes are unavailable to TextObjects:
> (The following are not applicable to TextObject, WrappingTextObject, PointObject or UseObject.)
> linecolour: colour of the "stroke" or outline of the shape
> linewidth: width of the outline of the shape (its "stroke-width")
> fillcolour: colour of the interior of the shape (not applicable to LineObject). Use "none" if no fill desired.
However, those attributes are needed to change the colour of the presented text - otherwise it is always black.

From [Mozilla](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text):
> ...
>     /* Note that the color of the text is set with the    *
>      * fill property, the color property is for HTML only */
> ...
A workaround is to use brython's `browser.svg.text` method but the positioning features of `TextObject` are superior.

Is it possible to remove this limitation?

**Comment by andy31lewis** [comment]
Hi Paul

`TextObjects` (and `WrappingTextObjects`) are something I am planning to develop further.  For example for brycharts I wanted them to be able to have a background colour, which is not possible at the moment. And in some circumstances it might be nice to be able to drag `TextObjects` in the same way as all the other objects.

Anyway, for the moment I have given them three more parameters. `textcolour` sets the colour of the text (ie the `fill`) and defaults to `"black"`. `linecolour` and `linewidth` set the colour and width of an outline round the text (ie the `stroke`) and default to `"none"` and `1` respectively (though I don't recommend using them except at large font sizes because the result in general doesn't look very good).

I hope that will meet your needs, get back to me if you need other features.

Best wishes

Andy

**Comment by kronenpj** [comment]
Andy,

  That sounds great. Unfortunately, I think I've done something wrong while trying to use it.  This is a snippet of code I tried:
```python
text = SVG.TextObject(
    string=f"{player_name}",
    anchorposition=(
        CARD_WIDTH * 0.75 * (counter - 1.5),
        CARD_HEIGHT * 0.75,
    ),
    anchorpoint=2,
    fontsize=24,
    textcolour="white",
    objid=f"name_{deck_type}{counter}",
)
canvas <= text
```
Where `CARD_WIDTH`, `CARD_HEIGHT` and `counter` are integers and `player_name` and `deck_type` are strings.

This throws: `TextObject: Caught exception: TypeError('int' object is not iterable)`

While this (roughtly equivalent) chunk works fine:
```python
text = browser.svg.text(
    f"{player_name}",
    x=CARD_WIDTH * 0.75 * (counter - 1.5),
    y=CARD_HEIGHT * 0.85,
    text_anchor="middle",
    font_size=24,
    style={"stroke": "white", "fill": "white"},
    id=f"name_{deck_type}{counter}",
)
canvas <= text
```

**Comment by andy31lewis** [comment]
Hi Paul

You have swapped `anchorpoint` and `anchorposition`: `anchorpoint` is the coordinates, and `anchorposition` the position of the `anchorpoint` relative to the text (1 to 9).

Hope that helps,

Andy

**Comment by kronenpj** [comment]
That does indeed! Of course, it works as advertised when used correctly.

I think I've either been programming too many hours over the weekends or too late into the evenings. :)

Thanks for your patience!
